# Demo installation
- name: Install Notepad++ version 6.6
  hosts: windows
  tasks:
    - name: Install notepadplusplus version 6.6
      win_chocolatey:
        name: notepadplusplus
        version: '6.6'
        state: present
- name: Install Mozilla Firefox version 108.0.1
  hosts: windows
  tasks:
    - name: Install Mozilla Firefox version 108.0.1
      win_chocolatey:
        name: firefox
        version: 108.0.1
        state: present