# Create GodMode super user settings
- name: Create the GodMode folder on the Desktop
  hosts: windows
  tasks:
    - name: Create the GodMode folder 
      ansible.windows.win_file:
        path: C:\Users\user\Desktop\GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}
        state: directory

# Downloading ShutUp10
- name: Download O&O ShutUp10
  hosts: windows
  tasks:
    - name: Download ShutUp10 to the Downloads folder
      ansible.windows.win_get_url:
        url: https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe
        dest: C:\Users\user\Downloads\OOSU10.exe

# Downlaoding FastRawViewer
- name: Download FastRawViewer
  hosts: windows
  tasks:
    - name: Download FastRawViewer to the Downloads folder
      ansible.windows.win_get_url:
        url: https://updates.fastrawviewer.com/data/FastRawViewer-2.0.7.1989-x64-Setup.exe
        dest: C:\Users\user\Downloads\FastRawViewer-2.0.7.1989-x64-Setup.exe

# Install Virtual Machine Platform from Windows Optional Features
- name: Install Virtual Machine Platform
  hosts: windows
  tasks:
    - name: Install Virtual Machine Platform
      ansible.windows.win_optional_feature:
        name: VirtualMachinePlatform
        state: present

# Install Windows Subsystem for Linux from Windows Optional Features
- name: Install Windows Subsystem for Linux
  hosts: windows
  tasks:
    - name: Install Microsoft Subsystem for Linux
      ansible.windows.win_optional_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present

# Install Windows Updates
- name: Install all updates and reboot as many times as needed
  hosts: windows
  tasks:
    - name: Install all Windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: 'yes'

- name: Install all updates and reboot as many times as needed
  hosts: windows
  tasks:
    - name: Install all Windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: 'yes'