# Install Virtual Machine Platform from Windows Optional Features
- name: Install Virtual Machine Platform
  hosts: windows
  tasks:
    - name: Install Virtual Machine Platform
      ansible.windows.win_optional_feature:
        name: VirtualMachinePlatform
        state: present

# Install Windows Subsystem for Linux from Windows Optional Features
- name: Install Windows Subsystem for Linux
  hosts: windows
  tasks:
    - name: Install Microsoft Subsystem for Linux
      ansible.windows.win_optional_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present

# Install Windows Updates
- name: Install all updates and reboot as many times as needed
  hosts: windows
  tasks:
    - name: Install all Windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: 'yes'

- name: Install all updates and reboot as many times as needed
  hosts: windows
  tasks:
    - name: Install all Windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: 'yes'